name = "cloudflare-docker-proxy"
workers_dev = true
main = "src/index.js"
compatibility_date = "2021-12-07"
routes = [
  { pattern = "docker.yjgs.eu.org", custom_domain = true },
  { pattern = "quay.yjgs.eu.org", custom_domain = true },
  { pattern = "gcr.yjgs.eu.org", custom_domain = true },
  { pattern = "k8s-gcr.yjgs.eu.org", custom_domain = true },
  { pattern = "k8s.yjgs.eu.org", custom_domain = true },
  { pattern = "ghcr.yjgs.eu.org", custom_domain = true },
  { pattern = "cloudsmith.yjgs.eu.org", custom_domain = true },
  { pattern = "docker.yjgs.eu.org/*", zone_name = "yjgs.eu.org" },
  { pattern = "quay.yjgs.eu.org/*", zone_name = "yjgs.eu.org" },
  { pattern = "gcr.yjgs.eu.org/*", zone_name = "yjgs.eu.org" },
  { pattern = "k8s-gcr.yjgs.eu.org/*", zone_name = "yjgs.eu.org" },
  { pattern = "k8s.yjgs.eu.org/*", zone_name = "yjgs.eu.org" },
  { pattern = "ghcr.yjgs.eu.org/*", zone_name = "yjgs.eu.org" },
  { pattern = "cloudsmith.yjgs.eu.org/*", zone_name = "yjgs.eu.org" },
]

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"
upstream_protocol = "https"

[vars]
MODE = "production"
LOCAL_ADDRESS = ""
TARGET_UPSTREAM = ""

[env.dev.vars]
MODE = "debug"
LOCAL_ADDRESS = "http://192.168.10.102:8787"
TARGET_UPSTREAM = "https://registry-1.docker.io"
